#!/bin/bash

# Build docker image
git clone https://github.com/devilcoders/dokku-md-dockerfiles /tmp/dokku-md-dockerfiles
docker build -q=true -t kloadut/mariadb /tmp/dokku-md-dockerfiles
rm -rf /tmp/dokku-md-dockerfiles
